list:
# vim-related symlinks
 - from: "./vim/vimrc"
   to: "~/.vimrc"
 - from: "./vim"
   to: "~/.vim"
 - from: "vim/ideavimrc"
   to: "~/.ideavimrc"
# git-related symlinks
 - from: "./git/gitconfig"
   to: "~/.gitconfig"
 - from: "./git/gitignore"
   to: "~/.gitignore"
# zsh-related symlinks
 - from: "./zsh/zplugin"
   to: "~/.zplugin"
 - from: "./zsh/.zshrc"
   to: "~/.zshrc"
# other symlinks
#  - from: "./ssh"
#    to: "~/.ssh"
# - from: "./others/hyper.js"
#   to: "~/.hyper.js"
# - from: ""
#   to: ""
